### ISSUE TITLE
Set::Object brings quite a bit with it

### ISSUE THREAD

**Issue by briandfoy** [graphviz-perl/Graph#17]
That's not to say that you need to do anything, so this could just be feedback. 

Although the original versions of this module had its problems, it was lightweight and easy to use. It hasn't had a major version bump but now it's a much different experience. 

I noticed that my CI builds have been taking much longer and I've traced it back to the inclusion of Set::Object in this module. It has a "recommends" dependency on Moose, which explodes the runtime by about 400%. I can do various things to turn that off, but not testing dependencies is something I'd rather not do.

I'm likely to drop this module because it's now much too heavy for my uses. I'm thinking about choosing some earlier version to use internally. Moose and everything else that comes with it is just too much of a maintenance hassle, no matter what convenience its users see at the code level.

**Comment by mohawk2** [comment]
Moose is indeed a runtime-recommends dependency of Set::Object. I think that the area for improvement here is your CI shouldn't install "recommends". Too bad if you feel you want to drop Make.

Major version-bumps are for when stuff gets broken, i.e. taken away. The subjective idea of "experience" (apparently based on installing dependencies' recommendations) isn't really a comparable notion as far as I can make out. Have you considered raising an issue on https://rt.cpan.org/Dist/Display.html?Name=Set-Object (it doesn't use GitHub issues)? I confess I don't see a great reason for it to recommend Moose, and probably it should be a develop.requires instead.

**Comment by mohawk2** [comment]
In fact, I have opened an issue there since it appears to me to be a mistake that it's a runtime-recommend: https://rt.cpan.org/Ticket/Display.html?id=134034

**Comment by briandfoy** [comment]
I can handle it in CI, as I said, but I don't want users to be bitten by this either.  People who want to create packages of their installed applications don't want all the extra stuff either.

But, it's feedback for you. Like I said, this used to be a lightweight module.
