### ISSUE TITLE
POD typo: unusable -> unusual

### ISSUE THREAD

**Issue by jonassmedegaard** [graphviz-perl/Graph#23]
POD section "Connected Graphs and Their Components" talks about Perl objects...
> blessed into a package with a rather unusable name.

Are they really unusable?  Seems that should instead say "unusual".

**Comment by mohawk2** [comment]
Thanks for the report! I don't think the usual-ness of the packages would be worth commenting on (I didn't write that text). If you want to experiment with the `refvertexed`/`connected_graph` functionality with Perl object vertices, and suggest more detailed docs (or even better, tests that show any bugs), please do.

For now, I'm going to close this, but please reopen it with thoughts on the above if you have any!
